# outputs average of n profits generated by the function that places your +EV bet

# inputs:
# bonus_odds   the odds used for each bonus bet
# bonus_bets   the number of the bonus bets which are bet. 5- bonus_bets would be the number converted
# n            the number of runs

# outputs:
# avg_profit

# notes on improvements and additions to function


#---------------------------------------------------------------------------------------------------------------------------------------------------


ev_bet_profit <- function(oddsjam_odd_1 = 131,
                          oddsjam_odd_2 = -175,
                          bad_odd = 300,
                          stake = 20) {

  # initialize
  # profit for our single run
  profit <- 0
  # avg profit
  avg_profit <- 0
  # fair win probability
  fair_win_p <- no_vig_p(
    oddsjam_odd_1,
    oddsjam_odd_2
  )

  # is this change here accurate for +EV odds?
  if (runif(1) < fair_win_p) {
    # win the bonus bet. Note that we only get the payout, 
      # no stake back w/free bet play
    profit <- stake * payout_fraction(bad_odd)
    # print(paste("bonus win",profit))
  } else {
    profit <- profit - stake
    # print(paste("bonus loss",profit))
  }
  return(profit)
}